/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class solarbeam_2_easydevices_jni_HitecServoMotor */

#ifndef _Included_solarbeam_2_easydevices_jni_HitecServoMotor
#define _Included_solarbeam_2_easydevices_jni_HitecServoMotor
#ifdef __cplusplus
extern "C" {
#endif
#undef solarbeam_2_easydevices_jni_HitecServoMotor_DEFAULT_NET_DUTY_MICROSECONDS
#define solarbeam_2_easydevices_jni_HitecServoMotor_DEFAULT_NET_DUTY_MICROSECONDS 1500L
/*
 * Class:     solarbeam_2_easydevices_jni_HitecServoMotor
 * Method:    constructHS785HBJni
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_solarbeam_12_easydevices_jni_HitecServoMotor_constructHS785HBJni
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     solarbeam_2_easydevices_jni_HitecServoMotor
 * Method:    destroyHS785HBJni
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_solarbeam_12_easydevices_jni_HitecServoMotor_destroyHS785HBJni
  (JNIEnv *, jobject, jlong);

/*
 * Class:     solarbeam_2_easydevices_jni_HitecServoMotor
 * Method:    enableJni
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_solarbeam_12_easydevices_jni_HitecServoMotor_enableJni
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     solarbeam_2_easydevices_jni_HitecServoMotor
 * Method:    setPositionDegreesJni
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_solarbeam_12_easydevices_jni_HitecServoMotor_setPositionDegreesJni
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     solarbeam_2_easydevices_jni_HitecServoMotor
 * Method:    getPositionDegreesJni
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_solarbeam_12_easydevices_jni_HitecServoMotor_getPositionDegreesJni
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
