/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class solarbeam_2_easydevices_jni_LightSensor */

#ifndef _Included_solarbeam_2_easydevices_jni_LightSensor
#define _Included_solarbeam_2_easydevices_jni_LightSensor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     solarbeam_2_easydevices_jni_LightSensor
 * Method:    constructLightSensorJni
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_solarbeam_12_easydevices_jni_LightSensor_constructLightSensorJni
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     solarbeam_2_easydevices_jni_LightSensor
 * Method:    destroyLightSensorJni
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_solarbeam_12_easydevices_jni_LightSensor_destroyLightSensorJni
  (JNIEnv *, jobject, jlong);

/*
 * Class:     solarbeam_2_easydevices_jni_LightSensor
 * Method:    isDevicePresentJni
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_solarbeam_12_easydevices_jni_LightSensor_isDevicePresentJni
  (JNIEnv *, jobject, jlong);

/*
 * Class:     solarbeam_2_easydevices_jni_LightSensor
 * Method:    powerOnJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_solarbeam_12_easydevices_jni_LightSensor_powerOnJni
  (JNIEnv *, jobject, jlong);

/*
 * Class:     solarbeam_2_easydevices_jni_LightSensor
 * Method:    powerOffJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_solarbeam_12_easydevices_jni_LightSensor_powerOffJni
  (JNIEnv *, jobject, jlong);

/*
 * Class:     solarbeam_2_easydevices_jni_LightSensor
 * Method:    readJni
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_solarbeam_12_easydevices_jni_LightSensor_readJni
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
