/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class solarbeam_2_easydevices_jni_CRIOModule */

#ifndef _Included_solarbeam_2_easydevices_jni_CRIOModule
#define _Included_solarbeam_2_easydevices_jni_CRIOModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     solarbeam_2_easydevices_jni_CRIOModule
 * Method:    FPGASetup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_solarbeam_12_easydevices_jni_CRIOModule_FPGASetup
  (JNIEnv *, jobject);

/*
 * Class:     solarbeam_2_easydevices_jni_CRIOModule
 * Method:    FPGAClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_solarbeam_12_easydevices_jni_CRIOModule_FPGAClose
  (JNIEnv *, jobject);

/*
 * Class:     solarbeam_2_easydevices_jni_CRIOModule
 * Method:    readAnalog
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_solarbeam_12_easydevices_jni_CRIOModule_readAnalog
  (JNIEnv *, jobject, jint);

/*
 * Class:     solarbeam_2_easydevices_jni_CRIOModule
 * Method:    readDigital
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_solarbeam_12_easydevices_jni_CRIOModule_readDigital
  (JNIEnv *, jobject);

/*
 * Class:     solarbeam_2_easydevices_jni_CRIOModule
 * Method:    setDirectionDigital
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_solarbeam_12_easydevices_jni_CRIOModule_setDirectionDigital
  (JNIEnv *, jobject, jint);

/*
 * Class:     solarbeam_2_easydevices_jni_CRIOModule
 * Method:    writeDigital
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_solarbeam_12_easydevices_jni_CRIOModule_writeDigital
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
